// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-leads.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/_helpers.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function loadKey(ctx, key, fallback) {
  const sb = supabaseForUser(ctx);
  const { data, error } = await sb.from("user_storage").select("value").eq("user_id", ctx.getUserId()).eq("key", key).maybeSingle();
  if (error) throw new Error(error.message);
  return data?.value ?? fallback;
}
async function saveKey(ctx, key, value) {
  const sb = supabaseForUser(ctx);
  const { error } = await sb.from("user_storage").upsert(
    { user_id: ctx.getUserId(), key, value, updated_at: (/* @__PURE__ */ new Date()).toISOString() },
    { onConflict: "user_id,key" }
  );
  if (error) throw new Error(error.message);
}
function text(payload, structured) {
  const t = typeof payload === "string" ? payload : JSON.stringify(payload, null, 2);
  return {
    content: [{ type: "text", text: t }],
    ...structured ? { structuredContent: structured } : {}
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) throw new Error("N\xE3o autenticado");
}

// src/lib/mcp/tools/list-leads.ts
var list_leads_default = defineTool({
  name: "list_leads",
  title: "Listar leads",
  description: "Lista os leads do usu\xE1rio. Suporta filtros por etapa (stage), cidade, nicho, texto livre em empresa/contato e limite. Use para responder perguntas do tipo 'quantos leads na etapa X' ou 'leads da cidade Y'.",
  inputSchema: {
    stage: z.string().optional().describe("Nome exato da etapa (ex.: 'Reuni\xE3o Marcada', 'Ganho')."),
    city: z.string().optional(),
    niche: z.string().optional(),
    search: z.string().optional().describe("Texto livre buscando em empresa, contato ou telefone."),
    limit: z.number().int().min(1).max(500).optional().describe("M\xE1ximo de leads a retornar (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    requireAuth(ctx);
    const leads = await loadKey(ctx, "p21_leads", []);
    const limit = input.limit ?? 50;
    const q = (input.search ?? "").trim().toLowerCase();
    const filtered = leads.filter((l) => {
      if (input.stage && l.stage !== input.stage) return false;
      if (input.city && (l.city ?? "").toLowerCase() !== input.city.toLowerCase()) return false;
      if (input.niche && (l.niche ?? "").toLowerCase() !== input.niche.toLowerCase()) return false;
      if (q) {
        const hay = `${l.company} ${l.contact} ${l.phone}`.toLowerCase();
        if (!hay.includes(q)) return false;
      }
      return true;
    });
    const items = filtered.slice(0, limit).map((l) => ({
      id: l.id,
      company: l.company,
      contact: l.contact,
      phone: l.phone,
      niche: l.niche,
      city: l.city,
      stage: l.stage,
      icpStars: l.icpStars,
      contractValue: l.contractValue,
      serviceType: l.serviceType,
      createdAt: l.createdAt,
      stageChangedAt: l.stageChangedAt
    }));
    return text(
      { total: filtered.length, returned: items.length, leads: items },
      { total: filtered.length, returned: items.length }
    );
  }
});

// src/lib/mcp/tools/get-lead.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_lead_default = defineTool2({
  name: "get_lead",
  title: "Detalhes do lead",
  description: "Retorna todos os dados de um lead pelo ID, incluindo notas e anexos.",
  inputSchema: {
    id: z2.string().min(1).describe("ID do lead.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    requireAuth(ctx);
    const leads = await loadKey(ctx, "p21_leads", []);
    const found = leads.find((l) => l.id === id);
    if (!found) return errorResult(`Lead ${id} n\xE3o encontrado.`);
    return text(found, { id });
  }
});

// src/lib/mcp/tools/create-lead.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var STAGE_DEFAULTS = {
  cold_call: "N\xE3o Contatado",
  oportunidades: "Reuni\xE3o Marcada",
  onboarding: "Contrato Assinado"
};
var create_lead_default = defineTool3({
  name: "create_lead",
  title: "Criar lead",
  description: "Cria um novo lead. Se 'stage' n\xE3o for informado, entra na primeira etapa do pipeline escolhido (default: cold_call).",
  inputSchema: {
    company: z3.string().min(1).describe("Nome da empresa."),
    contact: z3.string().optional().describe("Nome do contato/decisor."),
    phone: z3.string().optional(),
    niche: z3.string().optional(),
    city: z3.string().optional(),
    pipeline: z3.enum(["cold_call", "oportunidades", "onboarding"]).optional(),
    stage: z3.string().optional().describe("Nome da etapa (sobrescreve o default do pipeline)."),
    icpStars: z3.number().int().min(1).max(3).optional(),
    contractValue: z3.number().optional(),
    serviceType: z3.string().optional(),
    notes: z3.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async (input, ctx) => {
    requireAuth(ctx);
    const pipeline = input.pipeline ?? "cold_call";
    const now = (/* @__PURE__ */ new Date()).toISOString();
    const stage = input.stage ?? STAGE_DEFAULTS[pipeline];
    const lead = {
      id: crypto.randomUUID(),
      company: input.company,
      contact: input.contact ?? "",
      phone: input.phone ?? "",
      niche: input.niche ?? "",
      city: input.city ?? "",
      gmnLink: "",
      instagramLink: "",
      icpStars: input.icpStars ?? 2,
      runsAds: false,
      stage,
      createdAt: now,
      stageChangedAt: now,
      notes: input.notes ?? "",
      attachments: [],
      contractValue: input.contractValue,
      serviceType: input.serviceType
    };
    const leads = await loadKey(ctx, "p21_leads", []);
    await saveKey(ctx, "p21_leads", [lead, ...leads]);
    return text(
      { ok: true, lead, message: `Lead "${lead.company}" criado em ${stage}. Recarregue o CRM para ver.` },
      { id: lead.id, stage }
    );
  }
});

// src/lib/mcp/tools/upcoming-meetings.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
var upcoming_meetings_default = defineTool4({
  name: "list_upcoming_meetings",
  title: "Pr\xF3ximas reuni\xF5es",
  description: "Lista reuni\xF5es agendadas nos pr\xF3ximos N dias (default 7), ordenadas cronologicamente.",
  inputSchema: {
    days: z4.number().int().min(1).max(60).optional().describe("Janela em dias (default 7).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    requireAuth(ctx);
    const window = days ?? 7;
    const meetings = await loadKey(ctx, "p21_meetings", []);
    const now = /* @__PURE__ */ new Date();
    const end = new Date(now.getTime() + window * 24 * 60 * 60 * 1e3);
    const parsed = meetings.map((m) => ({ m, at: /* @__PURE__ */ new Date(`${m.date}T${m.time || "00:00"}:00`) })).filter(({ at }) => at >= now && at <= end).sort((a, b) => a.at.getTime() - b.at.getTime()).map(({ m, at }) => ({ ...m, when: at.toISOString() }));
    return text({ window_days: window, count: parsed.length, meetings: parsed }, { count: parsed.length });
  }
});

// src/lib/mcp/tools/pipeline-summary.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^4.4.3";
var STAGE_KEYS = {
  cold_call: "p21_stages_cold_call",
  oportunidades: "p21_stages_oportunidades",
  onboarding: "p21_stages_onboarding"
};
var pipeline_summary_default = defineTool5({
  name: "pipeline_summary",
  title: "Resumo do pipeline",
  description: "Retorna, por etapa do pipeline escolhido, a contagem de leads e a soma de valores de contrato. \xDAtil para 'quanto tenho em negocia\xE7\xE3o' ou 'quantos leads em cada etapa'.",
  inputSchema: {
    pipeline: z5.enum(["cold_call", "oportunidades", "onboarding"]).describe("Qual pipeline resumir.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ pipeline }, ctx) => {
    requireAuth(ctx);
    const [leads, stages] = await Promise.all([
      loadKey(ctx, "p21_leads", []),
      loadKey(ctx, STAGE_KEYS[pipeline], [])
    ]);
    const stageSet = new Set(stages);
    const inPipeline = leads.filter((l) => stageSet.has(l.stage));
    const byStage = stages.map((stage) => {
      const rows = inPipeline.filter((l) => l.stage === stage);
      const total = rows.reduce((sum, l) => sum + (l.contractValue ?? 0), 0);
      return { stage, leads: rows.length, contractTotal: total };
    });
    const totals = {
      leads: inPipeline.length,
      contractTotal: inPipeline.reduce((s, l) => s + (l.contractValue ?? 0), 0)
    };
    return text({ pipeline, totals, stages: byStage }, totals);
  }
});

// src/lib/mcp/tools/log-call.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^4.4.3";
var log_call_default = defineTool6({
  name: "log_call_note",
  title: "Registrar nota de liga\xE7\xE3o",
  description: "Adiciona uma nota de liga\xE7\xE3o ao hist\xF3rico do lead. Use para logar retornos r\xE1pidos ('deixei recado', 'reagendou', 'sem interesse').",
  inputSchema: {
    leadId: z6.string().min(1),
    text: z6.string().min(1).describe("Conte\xFAdo da nota."),
    outcome: z6.enum(["conectou", "sem_resposta", "recado", "reagendou", "sem_interesse", "reuniao_marcada", "outro"]).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async (input, ctx) => {
    requireAuth(ctx);
    const leads = await loadKey(ctx, "p21_leads", []);
    const idx = leads.findIndex((l) => l.id === input.leadId);
    if (idx === -1) return errorResult(`Lead ${input.leadId} n\xE3o encontrado.`);
    const note = {
      id: crypto.randomUUID(),
      timestamp: (/* @__PURE__ */ new Date()).toISOString(),
      text: input.text,
      outcome: input.outcome
    };
    const updated = { ...leads[idx], callNotes: [note, ...leads[idx].callNotes ?? []] };
    const next = [...leads];
    next[idx] = updated;
    await saveKey(ctx, "p21_leads", next);
    return text({ ok: true, leadId: input.leadId, company: updated.company, note }, { id: note.id });
  }
});

// src/lib/mcp/index.ts
var projectRef = "mvfglrfcnzfrfgxsaagj";
var mcp_default = defineMcp({
  name: "performance21-mcp",
  title: "Performance21 CRM",
  version: "0.1.0",
  instructions: "Ferramentas do CRM Performance21. Permitem consultar leads, resumo do pipeline (Cold Call, Oportunidades, Onboarding), pr\xF3ximas reuni\xF5es, criar leads e registrar notas de liga\xE7\xF5es. Cada chamada roda como o usu\xE1rio autenticado; dados s\xE3o escopados por conta via RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_leads_default, get_lead_default, create_lead_default, upcoming_meetings_default, pipeline_summary_default, log_call_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
